const { connectDatabase, Question } = require('./db');

const questions = [
  // JavaScript
  { language: 'JavaScript', category: 'Basics', difficulty: 'Easy', question: 'What is the difference between let, const, and var?', answer: 'var is function-scoped and hoisted, let is block-scoped and not hoisted to usable state, const is block-scoped and cannot be reassigned. var allows redeclaration, let and const do not. const must be initialized at declaration.', code_example: 'var x = 1; // function scoped\nlet y = 2; // block scoped\nconst z = 3; // block scoped, immutable binding\n\nif (true) {\n  var a = 10; // accessible outside\n  let b = 20; // only inside block\n}\nconsole.log(a); // 10\nconsole.log(b); // ReferenceError' },
  { language: 'JavaScript', category: 'Basics', difficulty: 'Medium', question: 'What are closures in JavaScript?', answer: 'A closure is a function that remembers the variables from its outer scope even after the outer function has returned. Closures are created every time a function is created. They are useful for data privacy, factory functions, and maintaining state.', code_example: 'function counter() {\n  let count = 0;\n  return {\n    increment: () => ++count,\n    getCount: () => count\n  };\n}\nconst c = counter();\nc.increment();\nconsole.log(c.getCount()); // 1' },
  { language: 'JavaScript', category: 'Basics', difficulty: 'Medium', question: 'What is the event loop in JavaScript?', answer: 'The event loop is a mechanism that handles asynchronous operations. It continuously checks the call stack, and when empty, pushes callbacks from the task queue (macrotasks) and microtask queue (Promises) onto the stack. Microtasks have priority over macrotasks.', code_example: 'console.log("1");\nsetTimeout(() => console.log("2"), 0);\nPromise.resolve().then(() => console.log("3"));\nconsole.log("4");\n// Output: 1, 4, 3, 2' },
  { language: 'JavaScript', category: 'Basics', difficulty: 'Hard', question: 'Explain prototypal inheritance in JavaScript.', answer: 'JavaScript uses prototypal inheritance where objects inherit directly from other objects via the prototype chain. Every object has a [[Prototype]] link. When a property is accessed, JS walks up the prototype chain until it finds it or reaches null. This differs from classical inheritance in class-based languages.', code_example: 'const animal = {\n  speak() { return `${this.name} makes a sound`; }\n};\nconst dog = Object.create(animal);\ndog.name = "Rex";\nconsole.log(dog.speak()); // "Rex makes a sound"' },
  { language: 'JavaScript', category: 'OOP', difficulty: 'Medium', question: 'What is the difference between == and === in JavaScript?', answer: '== performs type coercion before comparison, converting operands to the same type. === is strict equality that checks both value and type without coercion. Always prefer === to avoid unexpected type conversion bugs.', code_example: 'console.log(1 == "1");   // true (coercion)\nconsole.log(1 === "1");  // false (strict)\nconsole.log(null == undefined);  // true\nconsole.log(null === undefined); // false' },

  // Python
  { language: 'Python', category: 'Basics', difficulty: 'Easy', question: 'What is the difference between a list and a tuple in Python?', answer: 'Lists are mutable (can be modified after creation) and use square brackets []. Tuples are immutable (cannot be changed) and use parentheses (). Tuples are faster and can be used as dictionary keys. Lists are better when you need to modify the collection.', code_example: '# List - mutable\nmy_list = [1, 2, 3]\nmy_list.append(4)  # OK\n\n# Tuple - immutable\nmy_tuple = (1, 2, 3)\n# my_tuple.append(4)  # Error!' },
  { language: 'Python', category: 'Basics', difficulty: 'Medium', question: 'What are decorators in Python?', answer: 'Decorators are functions that modify the behavior of other functions without changing their code. They use the @decorator syntax and are commonly used for logging, authentication, caching, and access control. A decorator takes a function as input and returns a new function.', code_example: 'def timer(func):\n    import time\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f"{func.__name__} took {time.time()-start:.2f}s")\n        return result\n    return wrapper\n\n@timer\ndef slow_func():\n    import time; time.sleep(1)\n\nslow_func()  # prints execution time' },
  { language: 'Python', category: 'OOP', difficulty: 'Medium', question: 'Explain the difference between @staticmethod and @classmethod.', answer: '@staticmethod does not receive any implicit first argument - it behaves like a regular function inside a class. @classmethod receives the class (cls) as the first argument and can access/modify class state. Use classmethod for factory methods and staticmethod for utility functions.', code_example: 'class MyClass:\n    count = 0\n    \n    @classmethod\n    def create(cls):\n        cls.count += 1\n        return cls()\n    \n    @staticmethod\n    def validate(value):\n        return isinstance(value, int)' },
  { language: 'Python', category: 'Data Structures', difficulty: 'Medium', question: 'What are list comprehensions and when to use them?', answer: 'List comprehensions provide a concise way to create lists using a single line of code. They are faster than traditional for loops and more readable for simple transformations. Use them for filtering and transforming data, but avoid for complex logic.', code_example: '# Traditional\nsquares = []\nfor x in range(10):\n    squares.append(x**2)\n\n# List comprehension\nsquares = [x**2 for x in range(10)]\n\n# With filter\nevens = [x for x in range(20) if x % 2 == 0]' },
  { language: 'Python', category: 'Basics', difficulty: 'Hard', question: 'What are generators and how do they differ from regular functions?', answer: 'Generators use yield instead of return to produce a sequence of values lazily, one at a time. They maintain state between calls and are memory-efficient for large datasets. Unlike regular functions that return all values at once, generators compute values on-demand.', code_example: 'def fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\nfor num in fibonacci(10):\n    print(num, end=" ")\n# 0 1 1 2 3 5 8 13 21 34' },

  // Java
  { language: 'Java', category: 'OOP', difficulty: 'Easy', question: 'What is the difference between abstract class and interface in Java?', answer: 'Abstract classes can have both abstract and concrete methods, constructors, and instance variables. Interfaces (pre-Java 8) only have abstract methods. Since Java 8, interfaces can have default and static methods. A class can implement multiple interfaces but extend only one abstract class.', code_example: 'abstract class Animal {\n    String name;\n    abstract void sound();\n    void breathe() { System.out.println("Breathing"); }\n}\n\ninterface Swimmable {\n    void swim();\n    default void float_() { System.out.println("Floating"); }\n}' },
  { language: 'Java', category: 'OOP', difficulty: 'Medium', question: 'Explain the SOLID principles.', answer: 'S-Single Responsibility: one class, one job. O-Open/Closed: open for extension, closed for modification. L-Liskov Substitution: subtypes must be substitutable for base types. I-Interface Segregation: prefer small specific interfaces. D-Dependency Inversion: depend on abstractions, not concretions.', code_example: '// Single Responsibility\nclass UserService {\n    void createUser(User u) { /* user logic */ }\n}\nclass EmailService {\n    void sendEmail(String to) { /* email logic */ }\n}\n\n// Dependency Inversion\ninterface Repository { void save(Object o); }\nclass UserRepo implements Repository {\n    public void save(Object o) { /* DB save */ }\n}' },
  { language: 'Java', category: 'Basics', difficulty: 'Easy', question: 'What is the difference between String, StringBuilder, and StringBuffer?', answer: 'String is immutable - every modification creates a new object. StringBuilder is mutable and not thread-safe (faster). StringBuffer is mutable and thread-safe (slower due to synchronization). Use StringBuilder for single-threaded string manipulation, StringBuffer for multi-threaded.', code_example: 'String s = "Hello";\ns = s + " World"; // creates new String object\n\nStringBuilder sb = new StringBuilder("Hello");\nsb.append(" World"); // modifies in place, fast\n\nStringBuffer sbf = new StringBuffer("Hello");\nsbf.append(" World"); // thread-safe' },
  { language: 'Java', category: 'Data Structures', difficulty: 'Medium', question: 'What is the difference between HashMap and TreeMap?', answer: 'HashMap stores key-value pairs with O(1) average lookup using hashing. It does not maintain order. TreeMap stores entries in sorted order (by key) using a Red-Black tree with O(log n) operations. Use HashMap for fast lookups, TreeMap when you need sorted keys.', code_example: 'Map<String, Integer> hashMap = new HashMap<>();\nhashMap.put("banana", 2);\nhashMap.put("apple", 1);\n// Order: unpredictable\n\nMap<String, Integer> treeMap = new TreeMap<>();\ntreeMap.put("banana", 2);\ntreeMap.put("apple", 1);\n// Order: apple, banana (sorted)' },
  { language: 'Java', category: 'Basics', difficulty: 'Hard', question: 'Explain Java memory management and garbage collection.', answer: 'Java divides memory into Heap (objects) and Stack (method frames, local variables). The heap is split into Young Generation (Eden, Survivor) and Old Generation. GC automatically reclaims unreferenced objects. Young Gen uses minor GC (frequent, fast), Old Gen uses major GC (infrequent, slower).', code_example: '// Objects are created on the heap\nObject obj = new Object(); // heap allocation\n\n// obj becomes eligible for GC when:\nobj = null; // no more references\n\n// You can suggest GC (not force it)\nSystem.gc();\n\n// Check memory\nRuntime rt = Runtime.getRuntime();\nSystem.out.println("Free: " + rt.freeMemory());' },

  // React
  { language: 'React', category: 'Framework-Specific', difficulty: 'Easy', question: 'What is the difference between state and props?', answer: 'Props are read-only data passed from parent to child components. State is mutable data managed within a component. Props flow down (unidirectional), state is local. When state changes, the component re-renders. Props cannot be modified by the receiving component.', code_example: '// Props - passed from parent\nfunction Greeting({ name }) {\n  return <h1>Hello, {name}!</h1>;\n}\n\n// State - managed internally\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}' },
  { language: 'React', category: 'Framework-Specific', difficulty: 'Medium', question: 'What is useEffect and when do you use it?', answer: 'useEffect is a hook for side effects in functional components: API calls, subscriptions, DOM manipulation. It runs after render. The dependency array controls when it re-runs. Empty array = run once on mount. No array = run every render. Return a cleanup function for subscriptions.', code_example: 'useEffect(() => {\n  // Runs on mount\n  const data = fetchAPI();\n  return () => {\n    // Cleanup on unmount\n  };\n}, []); // empty array = mount only\n\nuseEffect(() => {\n  // Runs when userId changes\n  fetchUser(userId);\n}, [userId]);' },
  { language: 'React', category: 'Framework-Specific', difficulty: 'Hard', question: 'What is React reconciliation and how does the virtual DOM work?', answer: 'React maintains a virtual DOM (lightweight JS representation of real DOM). On state change, React creates a new virtual DOM tree, diffs it with the previous one (reconciliation), and applies only the minimal necessary changes to the real DOM. It uses keys to track list items efficiently.', code_example: '// Keys help React identify which items changed\nfunction TodoList({ todos }) {\n  return (\n    <ul>\n      {todos.map(todo => (\n        <li key={todo.id}>{todo.text}</li>\n      ))}\n    </ul>\n  );\n}\n// Bad: key={index} - causes issues on reorder\n// Good: key={todo.id} - stable identity' },

  // Node.js
  { language: 'Node.js', category: 'Framework-Specific', difficulty: 'Easy', question: 'What is Node.js and why use it?', answer: 'Node.js is a JavaScript runtime built on Chrome V8 engine. It uses an event-driven, non-blocking I/O model making it efficient for I/O-heavy apps like APIs and real-time applications. It allows using JavaScript on the server side and has a huge npm ecosystem.', code_example: 'const http = require("http");\n\nconst server = http.createServer((req, res) => {\n  res.writeHead(200, { "Content-Type": "text/plain" });\n  res.end("Hello from Node.js!");\n});\n\nserver.listen(3000, () => {\n  console.log("Server running on port 3000");\n});' },
  { language: 'Node.js', category: 'Framework-Specific', difficulty: 'Medium', question: 'What is middleware in Express.js?', answer: 'Middleware functions have access to request, response, and the next function. They execute sequentially and can modify req/res objects, end the request cycle, or call next(). Used for logging, authentication, error handling, body parsing, and CORS.', code_example: '// Custom middleware\nconst logger = (req, res, next) => {\n  console.log(`${req.method} ${req.url}`);\n  next(); // pass to next middleware\n};\n\napp.use(logger);\n\n// Auth middleware\nconst auth = (req, res, next) => {\n  if (!req.headers.token) return res.status(401).send("Unauthorized");\n  next();\n};\napp.get("/protected", auth, handler);' },

  // SQL
  { language: 'SQL', category: 'Database', difficulty: 'Easy', question: 'What is the difference between WHERE and HAVING?', answer: 'WHERE filters rows before grouping (works on individual rows). HAVING filters groups after GROUP BY (works on aggregated results). WHERE cannot use aggregate functions, HAVING can. Use WHERE for row-level filtering and HAVING for group-level filtering.', code_example: '-- WHERE: filter before grouping\nSELECT department, COUNT(*) as emp_count\nFROM employees\nWHERE salary > 50000\nGROUP BY department;\n\n-- HAVING: filter after grouping\nSELECT department, AVG(salary) as avg_sal\nFROM employees\nGROUP BY department\nHAVING AVG(salary) > 60000;' },
  { language: 'SQL', category: 'Database', difficulty: 'Medium', question: 'Explain the different types of JOINs.', answer: 'INNER JOIN returns matching rows from both tables. LEFT JOIN returns all rows from left table + matching from right. RIGHT JOIN returns all from right + matching from left. FULL OUTER JOIN returns all rows from both tables. CROSS JOIN returns cartesian product.', code_example: 'SELECT e.name, d.dept_name\nFROM employees e\nINNER JOIN departments d ON e.dept_id = d.id;\n\nSELECT e.name, d.dept_name\nFROM employees e\nLEFT JOIN departments d ON e.dept_id = d.id;\n-- Includes employees without a department' },
  { language: 'SQL', category: 'Database', difficulty: 'Hard', question: 'What are indexes and how do they improve performance?', answer: 'Indexes are data structures (usually B-tree) that speed up data retrieval. They create a sorted reference to rows, allowing O(log n) lookups instead of O(n) full table scans. However, they slow down INSERT/UPDATE operations and use extra storage. Use on frequently queried columns.', code_example: 'CREATE INDEX idx_email ON users(email);\n\n-- Composite index\nCREATE INDEX idx_name_dept\nON employees(last_name, department);\n\n-- Unique index\nCREATE UNIQUE INDEX idx_unique_email\nON users(email);\n\n-- Check if index is used\nEXPLAIN ANALYZE\nSELECT * FROM users WHERE email = \'john@test.com\';' },

  // TypeScript
  { language: 'TypeScript', category: 'Basics', difficulty: 'Easy', question: 'What is TypeScript and why use it over JavaScript?', answer: 'TypeScript is a typed superset of JavaScript that compiles to plain JS. It adds static type checking, interfaces, enums, and generics. Benefits: catch errors at compile time, better IDE support, improved code documentation, easier refactoring in large codebases.', code_example: 'interface User {\n  id: number;\n  name: string;\n  email?: string; // optional\n}\n\nfunction greet(user: User): string {\n  return `Hello, ${user.name}!`;\n}\n\nconst user: User = { id: 1, name: "Alice" };\nconsole.log(greet(user));' },
  { language: 'TypeScript', category: 'Basics', difficulty: 'Medium', question: 'What are generics in TypeScript?', answer: 'Generics allow creating reusable components that work with multiple types while maintaining type safety. They act as type variables, letting you capture the type provided by the user. Common in functions, classes, and interfaces for collections, API responses, and utility types.', code_example: 'function identity<T>(arg: T): T {\n  return arg;\n}\n\nidentity<string>("hello"); // type: string\nidentity<number>(42);      // type: number\n\ninterface ApiResponse<T> {\n  data: T;\n  status: number;\n}\n\nconst res: ApiResponse<User[]> = {\n  data: [{ id: 1, name: "Alice" }],\n  status: 200\n};' },

  // C++
  { language: 'C++', category: 'Basics', difficulty: 'Easy', question: 'What is the difference between pointer and reference in C++?', answer: 'A pointer holds a memory address and can be null, reassigned, and used with pointer arithmetic. A reference is an alias for an existing variable, cannot be null, must be initialized at declaration, and cannot be reassigned. References are safer and simpler; pointers are more flexible.', code_example: 'int x = 10;\n\n// Pointer\nint* ptr = &x;\n*ptr = 20; // x is now 20\nptr = nullptr; // can be null\n\n// Reference\nint& ref = x;\nref = 30; // x is now 30\n// int& ref2; // Error: must initialize' },
  { language: 'C++', category: 'OOP', difficulty: 'Medium', question: 'What is virtual function and polymorphism in C++?', answer: 'Virtual functions enable runtime polymorphism. When a base class pointer/reference calls a virtual function, the derived class override is executed (dynamic dispatch via vtable). Without virtual, the base class version is called. Pure virtual functions (= 0) make a class abstract.', code_example: 'class Shape {\npublic:\n    virtual double area() = 0; // pure virtual\n    virtual ~Shape() {}\n};\n\nclass Circle : public Shape {\n    double r;\npublic:\n    Circle(double r) : r(r) {}\n    double area() override { return 3.14 * r * r; }\n};\n\nShape* s = new Circle(5);\ncout << s->area(); // 78.5 (dynamic dispatch)' },

  // Go
  { language: 'Go', category: 'Basics', difficulty: 'Easy', question: 'What are goroutines and how are they different from threads?', answer: 'Goroutines are lightweight concurrent functions managed by the Go runtime. They use only ~2KB of stack (vs ~1MB for OS threads), are multiplexed onto fewer OS threads, and communicate via channels. Starting a goroutine is as simple as adding "go" before a function call.', code_example: 'func main() {\n    ch := make(chan string)\n    \n    go func() {\n        ch <- "Hello from goroutine!"\n    }()\n    \n    msg := <-ch\n    fmt.Println(msg)\n}' },
  { language: 'Go', category: 'Basics', difficulty: 'Medium', question: 'What are channels in Go and when to use them?', answer: 'Channels are typed conduits for communication between goroutines. They can be buffered or unbuffered. Unbuffered channels synchronize sender and receiver. Buffered channels allow sending without a ready receiver up to the buffer size. Use select to multiplex on multiple channels.', code_example: 'ch := make(chan int, 3) // buffered channel\n\ngo func() {\n    for i := 0; i < 3; i++ {\n        ch <- i\n    }\n    close(ch)\n}()\n\nfor val := range ch {\n    fmt.Println(val) // 0, 1, 2\n}' },

  // HTML/CSS
  { language: 'HTML/CSS', category: 'Basics', difficulty: 'Easy', question: 'What is the CSS Box Model?', answer: 'Every HTML element is a box with four layers: content (innermost), padding (space around content), border (around padding), and margin (outermost space). box-sizing: border-box includes padding and border in the element width/height, making layouts more predictable.', code_example: '.box {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid black;\n  margin: 10px;\n  box-sizing: border-box;\n  /* Total width = 200px (border-box) */\n  /* Without border-box: 200+40+4 = 244px */\n}' },
  { language: 'HTML/CSS', category: 'Basics', difficulty: 'Medium', question: 'Explain Flexbox and when to use it vs Grid.', answer: 'Flexbox is one-dimensional layout (row OR column) for distributing space and aligning items. Grid is two-dimensional (rows AND columns) for complex layouts. Use Flexbox for navbars, card rows, centering. Use Grid for page layouts, dashboards, and complex arrangements.', code_example: '/* Flexbox - one direction */\n.nav {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n\n/* Grid - two dimensions */\n.dashboard {\n  display: grid;\n  grid-template-columns: 250px 1fr 1fr;\n  grid-template-rows: auto 1fr auto;\n  gap: 16px;\n}' },
];

async function seed() {
  try {
    await connectDatabase();
    
    // Clear existing seeded questions
    await Question.deleteMany({ is_user_added: false });
    
    const docs = questions.map(q => ({ ...q, is_user_added: false }));
    await Question.insertMany(docs);
    
    console.log(`✅ Seeded ${docs.length} questions successfully!`);
    if (require.main === module) process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    if (require.main === module) process.exit(1);
  }
}

if (require.main === module) {
  seed();
}

module.exports = { seed };

